services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "#barawakumbuka#"
      MYSQL_DATABASE: cricket
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p#barawakumbuka#"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - devops_network

  backend:
    build:
      context: ./demo
      dockerfile: dockerfile
    container_name: backend_container
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cricket?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "#barawakumbuka#"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    networks:
      - devops_network

  frontend:
    build: ./FrontEnd
    container_name: frontend_container
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://localhost:8081
      
    depends_on:
      - backend
    networks:
      - devops_network

networks:
  devops_network:
    driver: bridge

volumes:
  mysql-data: