services:

  backend:
    build:
      context: ./demo
      dockerfile: dockerfile
    container_name: backend_container
    ports:
      - "8081:8081"
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cricket?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_URL: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12817561
      SPRING_DATASOURCE_USERNAME: sql12817561
      SPRING_DATASOURCE_PASSWORD: "kZjUqKGpmR"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    networks:
      - devops_network

  frontend:
    build: ./FrontEnd
    container_name: frontend_container
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_URL: http://15.134.222.250:8081
      
    depends_on:
      - backend
    networks:
      - devops_network

networks:
  devops_network:
    driver: bridge


